const dataKegiatan = [
  {
    tanggal: "2025-03-16",
    namaKegiatan: "Sosialisasi Anti Pelecehan Seksual",
    lokasi: "Staiun Pasar Senen",
    absensi: [
  { nama: "Hery Haryadi", status: "Hadir" },
  { nama: "Arjuna Pamungkas", status: "Hadir" },
  { nama: "Mohammad Walid Ridho", status: "Hadir" },
  { nama: "Ridho Ariotama", status: "Alpa" },
  { nama: "Rasyiqha Syafa Rabanny", status: "Hadir" },
  { nama: "Salman Alparisi", status: "Hadir" },
  { nama: "Muhammad Rizky Hidayat", status: "Hadir" },
  { nama: "Fathir Ahmad Maulana", status: "Hadir" },
  { nama: "Eki Apriandi", status: "Hadir" },
  { nama: "Moch Fikri", status: "Hadir" },
  { nama: "Agil Pramono", status: "Hadir" },
  { nama: "Aldi Hadiansyah", status: "Hadir" },
  { nama: "Hasan Al Anwari", status: "Hadir" },
  { nama: "Muhammad Alfazely Wibisono", status: "Hadir" },
  { nama: "Abi Dzar Ismail", status: "Alpa" },
  { nama: "Adam Maliqi Saputra", status: "Alpa" },
  { nama: "Adnan Taqwa Junior", status: "Hadir" },
  { nama: "Agung Dwi Prasetyo", status: "Alpa" },
  { nama: "Ahmad Fauzan", status: "Hadir" },
  { nama: "Aldiko Araya", status: "Alpa" },
  { nama: "Alfaro Azmi Triamantyo", status: "Alpa" },
  { nama: "Almas Tito Rifa'i", status: "Alpa" },
  { nama: "Ananda Febriyanti", status: "Alpa" },
  { nama: "Asyazid Prasetyo Alfandhi", status: "Alpa" },
  { nama: "Danureza Setiabudi", status: "Hadir" },
  { nama: "Dimitri Setya", status: "Hadir" },
  { nama: "Dzakir Rafiqi Afkar", status: "Alpa" },
  { nama: "Eliezer Clarence Nadek", status: "Alpa" },
  { nama: "Farhanaprian", status: "Alpa" },
  { nama: "Ferdyansyah", status: "Alpa" },
  { nama: "Haidar Yahya", status: "Alpa" },
  { nama: "Ibnu Zaki", status: "Hadir" },
  { nama: "Irfan Maulana Wirawijaya", status: "Alpa" },
  { nama: "Johannaf Achsan Ard", status: "Alpa" },
  { nama: "M. Apriliyanto", status: "Hadir" },
  { nama: "Miqdad Ifzal Rao", status: "Alpa" },
  { nama: "Muhamad Fajri Ridho", status: "Hadir" },
  { nama: "Muhamad Fauzan", status: "Alpa" },
  { nama: "Muhamad Ridwan", status: "Alpa" },
  { nama: "Muhammad Hafiizh Abdurraafi", status: "Hadir" },
  { nama: "Muhammad Hery", status: "Alpa" },
  { nama: "Muhammad Rafka Ihza Pahlevi", status: "Hadir" },
  { nama: "Muhammad Rizky Kemal", status: "Alpa" },
  { nama: "Muhammad Rizieq Arsyad", status: "Hadir" },
  { nama: "Muhammad Sabiq Firdaus", status: "Hadir" },
  { nama: "Muhaimin Iskandar Khadafi", status: "Alpa" },
  { nama: "Nanda Risqi Ramadan", status: "Alpa" },
  { nama: "Raikhan Luluh Saputra", status: "Alpa" },
  { nama: "Ramadhan Arya Prayoga", status: "Alpa" },
  { nama: "Rubben Pradita", status: "Alpa" },
  { nama: "Satrya Try Ardhyanto", status: "Izin" },
  { nama: "Sulthan Shadiq Andra Tushyahbi", status: "Hadir" },
  { nama: "Yeskil Nathaniel", status: "Hadir" },
  { nama: "Yudi Kuswara", status: "Hadir" },
  { nama: "Zya Afif Aulia", status: "Alpa" }
]
},
  {
    tanggal: "2025-04-27",
    namaKegiatan: "Sosialisasi Anti Pelecehan Seksual",
    lokasi: "Staiun Jakarta Kota",
    absensi: [
  { nama: "Hery Haryadi", status: "Izin" },
  { nama: "Arjuna Pamungkas", status: "Izin", alasan: "Kerja" },
  { nama: "Mohammad Walid Ridho", status: "Hadir" },
  { nama: "Ridho Ariotama", status: "Hadir" },
  { nama: "Rasyiqha Syafa Rabanny", status: "Hadir" },
  { nama: "Salman Alparisi", status: "Hadir" },
  { nama: "Muhammad Rizky Hidayat", status: "Izin", alasan: "Kuliah" },
  { nama: "Fathir Ahmad Maulana", status: "Hadir" },
  { nama: "Eki Apriandi", status: "Hadir" },
  { nama: "Moch Fikri", status: "Hadir" },
  { nama: "Agil Pramono", status: "Hadir" },
  { nama: "Aldi Hadiansyah", status: "Alpa" },
  { nama: "Hasan Al Anwari", status: "Alpa" },
  { nama: "Muhammad Alfazely Wibisono", status: "Hadir" },
  { nama: "Abi Dzar Ismail", status: "Alpa" },
  { nama: "Abimulia Saleh", status: "Hadir" },
  { nama: "Adam Maliqi Saputra", status: "Alpa" },
  { nama: "Adnan Taqwa Junior", status: "Alpa" },
  { nama: "Agung Dwi Prasetyo", status: "Hadir" },
  { nama: "Ahmad Fauzan", status: "Hadir" },
  { nama: "Akbar Nurhidayanto", status: "Hadir" },
  { nama: "Akmal Wibisana", status: "Hadir" },
  { nama: "Aldiko Araya", status: "Alpa" },
  { nama: "Alfaro Azmi Triamantyo", status: "Alpa" },
  { nama: "Almas Tito Rifa'i", status: "Hadir" },
  { nama: "Alvi Anugerah", status: "Hadir" },
  { nama: "Alvito Bima Nurfaqih", status: "Hadir" },
  { nama: "Ananda Febriyanti", status: "Hadir" },
  { nama: "Andikha Firzatullah", status: "Izin", alasan: "Sakit" },
  { nama: "Ardi Firmansyah", status: "Hadir" },
  { nama: "Asyazid Prasetyo Alfandhi", status: "Alpa" },
  { nama: "Bilal Bani Adam", status: "Hadir" },
  { nama: "Danureza Setiabudi", status: "Izin" },
  { nama: "Daffa Ardiyansyah", status: "Hadir" },
  { nama: "Dimitri Setya", status: "Hadir" },
  { nama: "Dzakir Rafiqi Afkar", status: "Hadir" },
  { nama: "Eliezer Clarence Nadek", status: "Alpa" },
  { nama: "Fahrezy Rizky Haditya", status: "Hadir" },
  { nama: "Fahry Ihza Putra", status: "Alpa" },
  { nama: "Farhanaprian", status: "Alpa" },
  { nama: "Ferdyansyah", status: "Alpa" },
  { nama: "Fikri Akbar Sujana", status: "Alpa" },
  { nama: "Genevie Nofell", status: "Alpa" },
  { nama: "Giriyama Romero", status: "Alpa" },
  { nama: "Haidar Yahya", status: "Alpa" },
  { nama: "Ibnu Zaki", status: "Hadir" },
  { nama: "Idzhar Fatekhatul Ramdan", status: "Hadir" },
  { nama: "Indah Hurun Aeni", status: "Hadir" },
  { nama: "Irfan Maulana Wirawijaya", status: "Alpa" },
  { nama: "Johannaf Achsan Ard", status: "Hadir" },
  { nama: "Kelvin Nelson", status: "Hadir" },
  { nama: "Kenneth Alexander", status: "Hadir" },
  { nama: "Kenzhie Emeraldy Wibowo", status: "Alpa" },
  { nama: "M. Apriliyanto", status: "Hadir" },
  { nama: "Miqdad Ifzal Rao", status: "Alpa" },
  { nama: "Muhamad Fajri Ridho", status: "Hadir" },
  { nama: "Muhamad Fauzan", status: "Alpa" },
  { nama: "Muhamad Ridwan", status: "Alpa" },
  { nama: "Muhammad Ahnaf Ghifari", status: "Hadir" },
  { nama: "Muhammad Akram Indriawan", status: "Hadir" },
  { nama: "Muhammad Hafiizh Abdurraafi", status: "Hadir" },
  { nama: "Muhammad Hery", status: "Hadir" },
  { nama: "Muhammad Rafka Ihza Pahlevi", status: "Hadir" },
  { nama: "Muhammad Rizky Kemal", status: "Alpa" },
  { nama: "Muhammad Rizieq Arsyad", status: "Hadir" },
  { nama: "Muhammad Sabiq Firdaus", status: "Hadir" },
  { nama: "Muhammad Sidqi Rabbani", status: "Hadir" },
  { nama: "Muhaimin Iskandar Khadafi", status: "Hadir" },
  { nama: "Nanda Risqi Ramadan", status: "Alpa" },
  { nama: "Raikhan Luluh Saputra", status: "Alpa" },
  { nama: "Raihan Alzena", status: "Hadir" },
  { nama: "Raisya Anandita", status: "Alpa" },
  { nama: "Ramadhan Arya Prayoga", status: "Izin", alasan: "Urusan Keluarga" },
  { nama: "Raditya Hadi Sumantri", status: "Hadir" },
  { nama: "Riyandi Aziz", status: "Alpa" },
  { nama: "Rizky Aal Fathir", status: "Alpa" },
  { nama: "Rubben Pradita", status: "Alpa" },
  { nama: "Satrya Try Ardhyanto", status: "Hadir" },
  { nama: "Sulthan Shadiq Andra Tushyahbi", status: "Alpa" },
  { nama: "Vibie Reyhan Aban", status: "Hadir" },
  { nama: "Yeskil Nathaniel", status: "Hadir" },
  { nama: "Yudi Kuswara", status: "Alpa" },
  { nama: "Zya Afif Aulia", status: "Izin", alasan: "Urusan Keluarga" }
]
  },
  {
    tanggal: "2025-05-10",
    namaKegiatan: "Sosialisasi Disiplin Perlintasan",
    lokasi: "JPL 18 Pasar Minggu",
    absensi: [
  { nama: "Mohammad Walid Ridho", status: "Alpa" },
  { nama: "Ridho Ariotama", status: "Alpa" },
  { nama: "Rasyiqha Syafa Rabanny", status: "Alpa" },
  { nama: "Salman Alparisi", status: "Alpa" },
  { nama: "Muhammad Rizky Hidayat", status: "Alpa" },
  { nama: "Fathir Ahmad Maulana", status: "Alpa" },
  { nama: "Eki Apriandi", status: "Alpa" },
  { nama: "Moch Fikri", status: "Alpa" },
  { nama: "Agil Pramono", status: "Alpa" },
  { nama: "Hasan Al Anwari", status: "Alpa" },
  { nama: "Muhammad Alfazely Wibisono", status: "Alpa" },
  { nama: "Abi Dzar Ismail", status: "Alpa" },
  { nama: "Abimulia Saleh", status: "Alpa" },
  { nama: "Adam Maliqi Saputra", status: "Alpa" },
  { nama: "Adnan Taqwa Junior", status: "Alpa" },
  { nama: "Agung Dwi Prasetyo", status: "Alpa" },
  { nama: "Ahmad Fauzan", status: "Alpa" },
  { nama: "Akbar Nurhidayanto", status: "Alpa" },
  { nama: "Akmal Wibisana", status: "Alpa" },
  { nama: "Aldiko Araya", status: "Alpa" },
  { nama: "Alfaro Azmi Triamantyo", status: "Alpa" },
  { nama: "Almas Tito Rifa'i", status: "Alpa" },
  { nama: "Alvi Anugerah", status: "Alpa" },
  { nama: "Alvito Bima Nurfaqih", status: "Alpa" },
  { nama: "Ananda Febriyanti", status: "Alpa" },
  { nama: "Andikha Firzatullah", status: "Alpa" },
  { nama: "Ardi Firmansyah", status: "Alpa" },
  { nama: "Asyazid Prasetyo Alfandhi", status: "Alpa" },
  { nama: "Bilal Bani Adam", status: "Alpa" },
  { nama: "Danureza Setiabudi", status: "Alpa" },
  { nama: "Daffa Ardiyansyah", status: "Alpa" },
  { nama: "Dimitri Setya", status: "Alpa" },
  { nama: "Dzakir Rafiqi Afkar", status: "Alpa" },
  { nama: "Eliezer Clarence Nadek", status: "Alpa" },
  { nama: "Fahrezy Rizky Haditya", status: "Alpa" },
  { nama: "Fahry Ihza Putra", status: "Alpa" },
  { nama: "Farhanaprian", status: "Alpa" },
  { nama: "Ferdyansyah", status: "Alpa" },
  { nama: "Fikri Akbar Sujana", status: "Alpa" },
  { nama: "Genevie Nofell", status: "Alpa" },
  { nama: "Giriyama Romero", status: "Alpa" },
  { nama: "Haidar Yahya", status: "Alpa" },
  { nama: "Ibnu Zaki", status: "Alpa" },
  { nama: "Idzhar Fatekhatul Ramdan", status: "Alpa" },
  { nama: "Indah Hurun Aeni", status: "Alpa" },
  { nama: "Irfan Maulana Wirawijaya", status: "Alpa" },
  { nama: "Johannaf Achsan Ard", status: "Alpa" },
  { nama: "Kelvin Nelson", status: "Alpa" },
  { nama: "Kenneth Alexander", status: "Alpa" },
  { nama: "Kenzhie Emeraldy Wibowo", status: "Alpa" },
  { nama: "M. Apriliyanto", status: "Alpa" },
  { nama: "Miqdad Ifzal Rao", status: "Alpa" },
  { nama: "Muhamad Fajri Ridho", status: "Alpa" },
  { nama: "Muhamad Fauzan", status: "Alpa" },
  { nama: "Muhamad Ridwan", status: "Alpa" },
  { nama: "Muhammad Ahnaf Ghifari", status: "Alpa" },
  { nama: "Muhammad Akram Indriawan", status: "Alpa" },
  { nama: "Muhammad Hafiizh Abdurraafi", status: "Alpa" },
  { nama: "Muhammad Hery", status: "Alpa" },
  { nama: "Muhammad Rafka Ihza Pahlevi", status: "Alpa" },
  { nama: "Muhammad Rizky Kemal", status: "Alpa" },
  { nama: "Muhammad Rizieq Arsyad", status: "Alpa" },
  { nama: "Muhammad Sabiq Firdaus", status: "Alpa" },
  { nama: "Muhammad Sidqi Rabbani", status: "Alpa" },
  { nama: "Muhaimin Iskandar Khadafi", status: "Alpa" },
  { nama: "Nanda Risqi Ramadan", status: "Alpa" },
  { nama: "Raikhan Luluh Saputra", status: "Alpa" },
  { nama: "Raihan Alzena", status: "Alpa" },
  { nama: "Raisya Anandita", status: "Alpa" },
  { nama: "Ramadhan Arya Prayoga", status: "Alpa" },
  { nama: "Raditya Hadi Sumantri", status: "Alpa" },
  { nama: "Riyandi Aziz", status: "Alpa" },
  { nama: "Rizky Aal Fathir", status: "Alpa" },
  { nama: "Rubben Pradita", status: "Alpa" },
  { nama: "Satrya Try Ardhyanto", status: "Alpa" },
  { nama: "Sulthan Shadiq Andra Tushyahbi", status: "Alpa" },
  { nama: "Vibie Reyhan Aban", status: "Alpa" },
  { nama: "Yeskil Nathaniel", status: "Alpa" },
  { nama: "Yudi Kuswara", status: "Alpa" },
  { nama: "Zya Afif Aulia", status: "Alpa" }
]
}
];